version: '3.8'
services:
  scheduleapi:
    container_name: scheduleApi
    build: ./scheduleApi
    volumes:
      - ./scheduleApi/code:/usr/src/app
    networks:
      - scheduleViewer
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    depends_on:
      - db
  frontend:
    container_name: viewer
    build: ./viewer
    volumes:
      - ./viewer/code:/usr/src/app
    networks:
      - scheduleViewer
    ports:
      - "3020:3020"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=schedule
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  scheduleViewer:
    driver: bridge

volumes:
  db:
    driver: local