version: '3.8'
services:
  scheduleapi:
    container_name: scheduleApi
    build: ./scheduleApi
    volumes:
      - ./scheduleApi/code:/usr/src/app
    networks:
      - scheduleViewer
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  exceltojson:
    container_name: excelToJson
    build: ./excelToJson
    volumes:
      - ./excelToJson/code:/usr/src/app
    networks:
      - scheduleViewer
    ports:
      - "3030:3030"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  frontend:
    container_name: viewer
    build: ./viewer
    volumes:
      - ./viewer/code:/usr/src/app
    networks:
      - scheduleViewer
    ports:
      - "3020:3020"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  scheduleViewer:
    driver: bridge